# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - apiimperial

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_346ceeec0e8e43f5b32be57a8cac1ac9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c4ac96bfe86b4c30a0fa71a7022ee256 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_346ceeec0e8e43f5b32be57a8cac1ac9 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'apiimperial'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_caf78d123b654cdc9161a2d88d974275 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_346ceeec0e8e43f5b32be57a8cac1ac9 }}/appsvc/staticsite:${{ github.sha }}'